[package]
name = "tarsum"
description = "Like `tar -tf`, but it also includes a checksum of each file"
version = "0.2.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2024"
license = "Unlicense"
readme = "README.md"
repository = "https://github.com/asayers/tarsum"

[dependencies]
anyhow = "1.0.100"
blake3 = "1.8.2"
bpaf = { version = "0.9.20", features = ["derive"] }
bytesize = "2.1.0"
fileslice = { version = "0.6.0", features = ["tar"], default-features = false }
tar = "0.4.44"
